### ISSUE TITLE
[Android] Survey content

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-android#140]
Add Survey content support  in the mobile app.

[Link to content](https://learning-raccoonapis.sandbox.edx.org/course/course-v1:OrgX+Demo101+2023_Q2/block-v1:OrgX+Demo101+2023_Q2+type@sequential+block@55880ce6a25f4180983fa23b027c695f/block-v1:OrgX+Demo101+2023_Q2+type@vertical+block@5d37554a550e48c2b9f0d0c465768311)

![Image](https://github.com/openedx/openedx-app-android/assets/121940663/d357cdca-4430-4e91-b433-b35411b3a26a)
Note: Current edX app from store is shown in the attachment

**Comment by HamzaIsrar12** [comment]
I'm starting the review.
