### ISSUE TITLE
Android - Unable to sign-in through username 

### ISSUE THREAD

**Issue by hassan6190** [openedx/openedx-app-android#185]
**Description:**
When a user tries to login through the username instead of the email the user gets an invalid email error message

**Steps to Reproduce:**

- Install the openedX app
- Load the app
- Tap on the Sign-in button 
- Try to sign-in through username and password
- Notice the users gets an invalid error message

**Expected Behaviour:**
The user should be able to log in to the app through both username and email  

**Note:** Kindly see the attached screenshot
![Screenshot_20240116-145829_OpenEdX](https://github.com/openedx/openedx-app-android/assets/69966132/e6e4b839-e83d-4e2c-9b74-820b7cbff513)

**Comment by rnr** [comment]
@Hamza442 
A small favour - please add [iOS]/[Android] to the title of the issues. This helps when viewing the "All issues table".
Thank you
