### ISSUE TITLE
[Android] Theming Customization Improvements

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-android#192]
**Goal**
Simplify the theme configuration for builds of the new openedx mobile app

Slack: #wg-product-mobile
Requirement Definition: Not Drafted
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-android/issues/193
```

**Comment by farhan-arshad-dev** [comment]
Hi @k1rill 

I have identified a code improvement related to theming with config [pull request](https://github.com/openedx/openedx-app-android/pull/196/files#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R11). Propose to implement a check to verify if the platform directory does not exist, use the default `srcDir/OpenEdx' will be considered. This enhancement will be beneficial for the community, especially for those who wish to utilize default colors or themes during development.

**Comment by marcotuts** [comment]
Added final open task to Q2 bugs epic, marking this closed.
