### ISSUE TITLE
[Android] Add an alert dialog when downloaded video is deleted

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-android#221]
Need to add an alert dialog when a downloaded video is deleted:
**Case 1:** when deleting all saved content (by using the switch on the download panel)
**Case 2:** when deleting saved video from module

![Image](https://github.com/openedx/openedx-app-android/assets/121940663/eb3a2027-9f35-4350-ac0d-5d27eb738f26)

**Comment by marcotuts** [comment]
In offline mode PR
