### ISSUE TITLE
[Android] Empty name of subcategory displays in Discussions

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-android#247]
[**Link to content**](https://discussions.edx.org/course-v1:Meta+Spark201+3T2022/topics)

**Steps to reproduce:**
1. Open app 
2. Enroll for the Introduction to Advanced Spark AR Tools and Effects course
3. Open this course
4. Tap on the Discussions tab
5. Scroll the screen

**Result:** Empty name of subcategory displays in Discussions

**Expected result:** Empty name of subcategory should display as Unnamed subcategory.

**Attachment:** 
![Image](https://github.com/openedx/openedx-app-android/assets/121940663/555ba6f6-cfd4-40f2-a566-c289c4a6312e)

**Comment by HamzaIsrar12** [comment]
@moiz994, Should we use the same string `Unnamed subcategory` for the apps as well? FYI, we've been using the string `Untitled` for similar cases in market apps.

cc: @dixidroid

**Comment by moiz994** [comment]
We can use the same string `Unnamed subcategory` for the apps
