### ISSUE TITLE
[Android] Acess Token Refresh Mechanism

### ISSUE THREAD

**Issue by HamzaIsrar12** [openedx/openedx-app-android#83]
User sessions often require continuous access to our system, and currently, our access token management lacks a mechanism for seamless refresh. This poses a challenge as users are frequently interrupted due to expiring access tokens, resulting in a suboptimal user experience.

**Comment by marcotuts** [comment]
How does this overlap with the JWT Token work linked here? - https://github.com/orgs/openedx/projects/56/views/7?filterQuery=&pane=issue&itemId=41392390

Is this additional improvement to that for refresh specifically?

**Comment by HamzaIsrar12** [comment]
You linked the wrong issue. This is for Android: https://github.com/openedx/openedx-app-android/issues/59.

Yeap, it's a much-needed improvement. Looking back, the above issue should have tested the basic refresh flow for JWT auth. This is crucial to prevent unexpected logouts and make the user experience better. 

I've already done something about it by creating a [pull request](https://github.com/openedx/openedx-app-android/pull/84) that not only fixes the issue by adding the needed refresh mechanism but also makes it work better, which improves the whole system.

**Comment by marcotuts** [comment]
FYI @volodymyr-chekyrta  on related JWT effort - https://github.com/orgs/openedx/projects/56/views/7?filterQuery=&pane=issue&itemId=41392419 is the Android ticket not the iOS one linked above. Thanks for clarifying @HamzaIsrar12
