### ISSUE TITLE
[Mobile] [Android] X-Blocks are showing that `student_view_multi_device` is set to false

### ISSUE THREAD

**Issue by moiz994** [openedx/openedx-app-android#85]
The app displays HTML blocks for which `student_view_multi_device` is set to `false`, which it shouldn't.

**Acceptance Criteria**

- The app shouldn’t display the blocks/components in which student_view_multi_device is set to false. 
- Make competent navigation parity with the iOS app.

**Comment by marcotuts** [comment]
What does this flag do, is this the 'do not show on mobile' setting?

**Comment by moiz994** [comment]
Yes, I believe so. 
@HamzaIsrar12 please correct me if I'm wrong.

**Comment by HamzaIsrar12** [comment]
You are right, Moiz. If this flag is `true` for an HTML block, we won't display that XBlock on mobile. Instead, we'll show a **"View on Web"** or **"Not Available on Mobile"** type screen.

**Comment by marcotuts** [comment]
This can be closed now that PR 158 has merged is my understanding. closing for now, lmk if that is odd / incomplete!
