### ISSUE TITLE
[Android] FAQ

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-android#95]
User can access FAQ from the profile page to get more help and learn how to use the mobile app, visit our frequently asked questions.

![Image](https://github.com/openedx/openedx-app-android/assets/121940663/d5ad6b3d-cbb2-4ece-a07d-ce4b498c024e)

**Comment by moiz994** [comment]
Acceptance Criteria:

- Tapping the FAQ button should redirect the user to the mobile browser to a specified webpage
- Webpage is URL is configurable and maintained in the app config
- This should be implemented behind a feature flag
