### ISSUE TITLE
[Android] Support info - Terms of Service / Privacy Policies

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-android#96]
The edX Prod App has these links:

[edx Terms of Service](https://www.edx.org/edx-terms-service/)
[edX Privacy Policy](https://www.edx.org/edx-privacy-policy)

Open these links inside application.

![Image](https://github.com/openedx/openedx-app-android/assets/121940663/eadea4cd-edb3-4d86-8c21-f6b603b62c53)

**Comment by moiz994** [comment]
Details of the tinks in the Privacy section as per the attached screenshot.

These pages are webview based implementations within the app. 
These links are configurable in the config. They open webViews within the app.
For the Do Not Sell link we should maintain the slider state till the user logs out.

<img src="https://github.com/openedx/openedx-app-ios/assets/109789173/81346df3-39ce-4f1f-8389-2b661993b04f" width="350">

**Comment by moiz994** [comment]
Please note that for these links we should not show the buttons if the corresponding key in the config is empty.
