### ISSUE TITLE
[Android] Support info - Contact support

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-android#97]
User can access support email from profile page to get more help using the application.

![Image](https://github.com/openedx/openedx-app-android/assets/121940663/7d73e547-04eb-4bc4-8a33-8d227f3469de)

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-android/pull/160
```

**Comment by moiz994** [comment]
This functionality is already implemented in the RG app. It can be seen by tapping "Contact support" in the profile screen.

In our case, we would need to see if the copy needs to be updated for the button and also update the email-to information as we have a different support email. I think the email should be updateable in the config.

**Comment by k1rill** [comment]
@moiz994 There was a small issue with "Contact support" on Android. It tried to send email not only with email app, but with all messenger apps also. This was fixed in https://github.com/openedx/openedx-app-android/pull/160. It is also configurable with config in the develop branch right now.

**Comment by moiz994** [comment]
awesome, thanks for the update!
